apiVersion: apps/v1

kind: Deployment

metadata:
  name: html-app

spec:

  replicas: 2

  selector:
    matchLabels:
      app: html-app

  template:

    metadata:
      labels:
        app: html-app

    spec:

      containers:

        - name: html-app

          image: gkv9972/devops-html-app:v1

          ports:
            - containerPort: 80
